### ISSUE TITLE
Onli

### ISSUE THREAD

**Issue by zz7iiu** [progressify/pysunsky#1]
Shopping

**Comment by zz7iiu** [comment]
API

ApiOpenStep.jpg

اتفاقية الواجهة العامة
   1. نقطة نهاية API:
       http://www.sunsky-api.com
       عينة عنوان URL API: http://www.sunsky-api.com/openapi/category!getChildren.do
 2. المعايير الشائعة:
key: المفتاح api الذي حصلت عليه من منصة SUNSKY المفتوحة API.
 signature: التوقيع الخاص بالمعلمات ، يتم تكوينه بقيم المعلمات والسر الذي حصلت عليه من منصة SUNSKY open API.
 الانتباه: يجب فرز المعلمات بالاسم قبل جيل التوقيع.
3. تنسيق الإرجاع البيانات
       البيانات التي تم إرجاعها بتنسيق JSON.
     (أ) مثال النتيجة الناجحة:
           { result: "success", data: [{"id":1032,"code":"003","gmtCreated":"01/31/2013 00:00","name":"N Style Phone","parentId":408,"status":1}] }
    (ب) مثال النتيجة الفاشلة:
           { result: "error", messages: [  "The record you visiting does NOT exist." ] }
   4. مراقبة تردد الاتصال
      سيحدد SUNSKY تردد المكالمة API في حالة ما إذا كانت المكالمات الجماعية تطغى على الخوادم.
       يرجى الرجوع إلى هذا للحصول على معلومات التحكم في التردد: http://www.sunsky-api.com/admin/apiAccessControl!list.do
  انتباه: جميع المعلمات وقيم الإرجاع حساسة لحالة الأحرف.
واجهة 1: احصل على الأطفال من الفئة المحددة في المعلمات
    (أ) URL: /openapi/category!getChildren.do
    (ب) المعلمات:
          إذا لم يتم تمرير أي معلمة ، فستعرض API جميع الفئات.
          يمكنك تحديد المعلمات أدناه لتصفية الفئات التي تريد جلبها:
          * parentId: معرف الفئة ، الذي ترغب في الحصول على فئاته الفرعية المباشرة ، اختياري ؛
         * gmtModifiedStart: لجلب الفئات التي تم تغييرها منذ 'gmtModifiedStart' ، بتنسيق MM / dd / yyyy HH: mm: ss (بمعنى 10/31/2013 01:23:20) ، اختياري ؛
  (ج) النتيجة:
           ملخص:
          * إذا لم تقم بتمرير المعلمة parentId ، فسيتم إرجاع مصفوفة جميع الفئات ؛
           * إذا قمت بتحديد "0" للقيمة parentId ، فسيتم إرجاع مصفوفة من الفئات الأعلى ؛
           * إذا قمت بتحديد رقم آخر لـ parentId ، فسيتم إرجاع مصفوفة الفئات التابعة المباشرة ؛
          * إذا حددت تاريخًا لـ gmtModifiedStart ، فسيتم عرض مجموعة من الفئات على الإطلاق منذ أن يتم إرجاع "gmtModifiedStart" ؛
           مجالات:
          * id: المعرّف الفريد للفئة ؛
           * الرمز: رمز الفئة. يتم فرز أطفال الفئة حسب التعليمات البرمجية؛
           الاسم: الاسم الكامل للفئة ؛
          * shortName: يمكن أن يكون الاسم المختصر للفئة فارغًا ؛
           hsCode: قد يكون رمز HS الخاص بالمنتجات في الفئة فارغًا. إذا كان رمز النظام المنسق فارغًا ، فالرجاء التحقق من كود النظام المنسق للفئة الرئيسية ؛
           * status: حالة الفئة. انظر الملحق أ;
           * parentId معرف الفئة الرئيسية ؛
           * gmtModified: وقت التغيير ، بتنسيق MM / dd / yyyy HH: mm: ss (بمعنى 10/31/2013 01:23:20) ؛
     تلميح: كيفية الحصول على الفئات المتغيرة؟
            (1) قبل استدعاء API getChildren ، قم بتحميل وقت T0 المحفوظة مسبقًا من db / file ؛
            (2) استدعاء API getChildren مع gmtModifiedStart = T0 ، ستقوم بإرجاع الفئات التي تغيرت منذ T0 ؛
            (3) قم بتحديث db المحلي الخاص بك باستخدام بيانات الفئة التي تم إرجاعها بواسطة getChildren API؛
            (4) تحديث T0 إلى أقصى تعديل بين الفئات التي يتم إرجاعها من قبل API getChildren ، ثم حفظ T0 إلى db / file ؛
            (5) زيادة رقم الصفحة وكرر الخطوة 2 ~ 4 حتى ترجع API getChildren أية بيانات.
واجهة 2: منتجات البحث
    (أ) URL: /openapi/product!search.do 
   (ب) المعلمات:
           * categoryId: معرف الفئة ، الذي تريد البحث فيه داخل المنتجات (بما في ذلك فئاتها الفرعية) ، اختياري ؛
           * pageSize: حجم مجموعة المنتجات عاد ، تعيين الافتراضي إلى 40 ، الحد الأقصى هو 100 ؛
           * page: رقم الصفحة ، الافتراضي تعيين إلى 1؛
           * gmtModifiedStart: لجلب المنتجات التي تم تغييرها منذ 'gmtModifiedStart' ، بتنسيق MM / dd / yyyy HH: mm: ss (بمعنى 10/31/2013 01:22:31) ، اختياري ؛
           * status: حالة المنتجات التي تريد جلبها ، انظر الملحق ب ، اختياري ؛
           * brandName: اسم العلامة التجارية للمنتجات التي تريد إحضارها ، أي iPartsBuy ، Xiaomi ، Huawei ، Meizu ، اختياري ؛
    (ج) النتيجة:
           ملخص: 
           * تعيد واجهة برمجة التطبيقات هذه المنتجات التي تطابق الشروط التي حددتها.
           مجالات:
           * total: يتوافق رقم المنتج الإجمالي مع الشروط التي حددتها.
           * pageCount: إجمالي عدد الصفحات ، محسوبًا بtotal و pageSize.
           * result: مصفوفة تحتوي على سجلات المنتج ، راجع "openapi / product! detail.do" الخاص بالواجهة للحصول على التفاصيل.
      تلميح: كيفية الحصول على المنتج المتغير؟
            (1) قبل استدعاء واجهة برمجة تطبيقات البحث ، قم بتحميل وقت T0 المحفوظة مسبقًا من db / file ؛
            (2) استدعاء API البحث مع gmtModifiedStart = T0 ، فإنه سيعود المنتجات التي تغيرت منذ T0 ؛
            (3) قم بتحديث db المحلي الخاص بك باستخدام بيانات المنتج التي تم إرجاعها من خلال API البحث ؛
            (4) تحديث T0 إلى الحد الأقصى gmtModified بين المنتجات التي يتم إرجاعها بواسطة API البحث ، ثم حفظ T0 إلى db / file ؛
            (5) قم بزيادة رقم الصفحة وكرر الخطوة 2 إلى 4 حتى لا تؤدي واجهة برمجة التطبيقات للبحث إلى إرجاع أية بيانات ؛
الواجهة 3: احصل على تفاصيل المنتج المحدد
    (أ) URL: /openapi/product!detail.do 
    (ب) المعلمات:
           * itemNo: العنصر # للمنتج الذي تريد الحصول على التفاصيل.     
    (ج) النتيجة:
           ملخص:
           * تعيد API هذه المعلومات الكاملة للمنتج المحدد.
           مجالات:
           * id: المعرف الفريد للمنتج ؛
           * categoryId: معرف الفئة للمنتج ؛
           * itemNo: العنصر # من المنتج ؛
           * groupItemNo: العنصر الأساسي # للمنتج. إذا كان المنتج ليس نموذجًا متعددًا ، فسيكون العنصر # هو نفسه العنصر # ؛
           * name: اسم المنتج ؛
           * barcode: الباركود الخاص بالمنتج ؛
           * description: الوصف التفصيلي للمنتج ؛
           * leadTime: وصف وقت البدء. بمعنى "الشحن في نفس اليوم على الطلبات قبل الساعة 6 مساءً (GMT + 8)" ، "1 ~ 3 أيام" ، "2 ~ 5 أيام" ؛
           gmtListed: الوقت الذي تم فيه إدراج المنتج ، بتنسيق MM / dd / yyyy HH: mm: ss (بمعنى 10/31/2013 01:23:20). المنتجات التي يكون وقتها المحدد في آخر 90 يومًا من الوافدين الجدد ؛
           * gmtModified: وقت التغيير ، بتنسيق MM / dd / yyyy HH: mm: ss (بمعنى 10/31/2013 01:23:20) ؛
           * warehouse: مستودع التسليم للمنتج. أي CN أو HK أو RU ؛
           * stock: إذا كان المستودع مستودعًا من الخارج (NOT CN) ، فإن هذا الحقل يعطي كمية المخزون الحالية ؛
           * moq: الحد الأدنى لكمية ، الافتراضي إلى 1 ؛
           * brandName: إذا تم وصف المنتج ، فإنه يحتوي على اسم العلامة التجارية ، مثل "هواوي" ؛
           * modelLabel: إذا كان المنتج متعدد النماذج ، فإنه يشير إلى معيار التصنيف (بمعنى اللون والحجم ...).
           * modelList: إذا كان المنتج متعدد النماذج ، فهو عبارة عن مصفوفة من الطرز. 
                       كل عنصر في الصفيف هو زوج قيمة مفتاح ، والمفتاح هو العنصر # ، والقيمة هي وصف النموذج. 
                        بمعنى [{key: 'S-MPH-001'، value: 'White'}، {key: 'S-MPH-002'، value: 'Black'}]
           * optionList: عناصر مماثلة لقوائم. 
                       {
                              عرض: "نص" أو "صورة" ،
                             العناصر: [ {
                                     itemNo: "S-MPH-0002" ،
                                     keywords: "Plastic Case for S7"
                              } ]
                       }
           * price: السعر الحالي للمنتج ؛
           * priceList: أسعار الجملة من السعر ، وفقا لكمية الشراء.
                       كل عنصر في الصفيف هو زوج مفتاح القيمة ، والمفتاح هو الكمية ، والقيمة هي السعر المقابل.
                        بمعنى [{key: 2، value: '2.98'}، {key: 10، value: '2.49'}]
           * clearance: هل المنتج في التخليص؟
           * orgPrice: إذا كان المنتج في التخليص أو في الترقية ، يخزن هذا الحقل السعر الأصلي ؛
           * priceExpired: إذا كان المنتج في الترقية ، يخزن هذا الحقل تاريخ انتهاء الصلاحية ، بتنسيق MM / dd / yyyy HH: mm (أي 10/31/2013 00:00). قد يكون لاغيا
           * status: حالة المنتج. انظر الملحق ب ؛
           * unitWeight: وحدة وزن المنتج ؛
           * packQty: كمية المنتجات في حالة ؛
           * packWeight: وزن المنتجات في الصندوق ، في وحدة "كجم".
           * packLength & packWidth & packHeight: مكعب المنتج في الصندوق ، في وحدة 'mm' ؛
           * يحتوي على البطارية: هل يحتوي المنتج على بطارية؟ صحيحة أو خاطئة؛
           * giftItemNo: إذا كان المنتج يحتوي على هدية مجانية ، فإن هذا الحقل يحتوي على رقم الهدية # ؛
           * brands: إذا كان هذا المنتج نوعًا من الملحقات ، فإن هذا الحقل يسرد نماذج العلامة التجارية التي تتوافق معها. لم يتم إرجاع هذا الحقل بواسطة "/openapi/product !search.do".
                     على سبيل المثال: [{brand: {name: "Apple"}، models: [{name: "iPhone"}، {name: "iPad"}]}]
           * params: المعلمات الرئيسية للمنتج. لم يتم إرجاع هذا الحقل بواسطة "/openapi/product !search.do".
                     على سبيل المثال: [{name: "Connectivity"، values: ["WIFI"، "3G"، "GPS"]}]
الواجهة 4: قم بتنزيل صور المنتج المحدد
    (أ) URL: /openapi/product!getImages.do 
    (ب) المعلمات: 
           * itemNo: العنصر # للمنتج الذي تريد الحصول على التفاصيل.     
           * الحجم: حجم صور المنتج التي تفضلها ، بالبكسل ، اختياري.
                   الحجم الأقصى هو 800 ، وبعض العناصر القديمة 500.
           * العلامة المائية: نص العلامة المائية ، اختياري.
    (ج) النتيجة:
           ملخص: 
           * إذا لم يكن العنصر غير موجود ، فإن رمز الاستجابة هو 404 ، وإلا فسيتم إرجاع مسار zip.
واجهة 5: احصل على تغيير الصورة
    (أ) URL: /openapi/product!getImageChangeList.do 
    (ب) المعلمات: 
           * pageSize: حجم صفيف التغيير عاد ، تعيين الافتراضي إلى 40 ، الحد الأقصى هو 100 ؛
           * page: رقم الصفحة ، الافتراضي تعيين إلى 1؛
           * gmtModifiedStart: لجلب أرقام العناصر التي تم تغيير صورها منذ 'gmtModifiedStart' ، بتنسيق MM / dd / yyyy HH: mm: ss (أي 10/30/2016 11:14:01)؛
    (ج) النتيجة:
          ملخص:
           * total: يتطابق أرقام العناصر الإجمالية مع الشروط التي حددتها.
           * pageCount: إجمالي عدد الصفحات ، محسوبًا بtotal و pageSize.
           * result: يحتوي مصفوفة على رقم العنصر والوقت الذي تم فيه تحديث صوره. i.e. [{{"itemNo": "S-MPH-001"، "gmtModified": "10/31/2016 01:04:22"}]
     يرجى إعادة تنزيل صور المنتج التي تم إدراج رقم مادتها في قائمة التغيير.
      تلميح: كيفية الحصول على الصور المتغيرة؟
            (1) قبل استدعاء واجهة برمجة تطبيقات changelist ، قم بتحميل وقت T0 المحفوظة مسبقًا من db / file ؛
            (2) استدعاء API changelist مع gmtModifiedStart = T0 ، فإنه سيتم إرجاع العناصر التي تغيرت الصور الخاصة بها منذ T0؛
            (3) إعادة تحميل صور المنتج التي تم إدراج رقم مادتها في قائمة التغيير ؛
            (4) تحديث T0 إلى الحد الأقصى gmtModified بين العناصر التي يتم إرجاعها بواسطة واجهة برمجة تطبيقات changelist ، ثم حفظ T0 إلى db / file ؛
            (5) زيادة رقم الصفحة وكرر الخطوة 2 ~ 4 حتى ترجع API changelist أية بيانات؛
واجهة 6: احصل على قائمة البلاد للشحن
    (aأ) URL: /openapi/order!getCountries.do 
    (ب) المعلمات:
           NONE.
    (ج) النتيجة:
           ملخص:
           * الحصول على قائمة البلاد للشحن ، بما في ذلك الولايات / المحافظات إذا كانت موجودة.
           مجالات:
           * id: المعرّف الفريد للبلد ؛
           * code: رمز البلد ، متوافق مع ISO 3166 ؛
           * name: اسم البلد ؛
           * shipT State: هل يتم حساب تكلفة الشحن على أساس الولاية؟ ربما أقل تكلفة. خطأ صحيح؛
           * stateList: قائمة الولاية / المقاطعة الاختيارية للبلد ، الحقول على النحو التالي:
                   ** code: رمز الولاية / المقاطعة
                   ** name: اسم الولاية / المقاطعة ؛
واجهة 7: الحصول على الأسعار وتكاليف الشحن للعناصر
    (أ) URL: /openapi/order!getPricesAndFreights.do 
    (ب) المعلمات: 
           * countryId: المعرّف الفريد للبلد ؛
           * state: رمز الولاية لعنوان الشحن ، راجع "/openapi/order!getCountries.do" ، اختياري ؛
           * items.#.itemNo, items.#.qty:  قائمة العناصر لحساب الأسعار وتكاليف الشحن.
                   ** رقم # هو رقم صحيح لتمييز العناصر ،على سبيل المثال items.1.itemNo, items.2.itemNo...
                   ** itemNo: البند رقم المنتج ؛
                   ** qty: الكمية لهذا البند ؛
    (ج) النتيجة:
           ملخص: 
           * الحصول على الأسعار وتكاليف الشحن للعناصر.
          مجالات:
           * priceList: أسعار العناصر ، الحقول على النحو التالي:
                   ** productId: المعرف الفريد للمنتج ؛
                   ** itemNo: البند رقم المنتج ؛
                   ** qty: الكمية لهذا البند ؛
                   ** price: سعر الوحدة النهائي لهذا البند ؛
                   ** orgPrice: سعر الوحدة الأصلي لهذا البند ، قد يكون السعر النهائي أرخص.
                   **  amount: المبلغ الإجمالي الفرعي النهائي لهذا البند ؛
                   ** ORGAmount: المبلغ الإجمالي الفرعي الأصلي للعنصر ، قد يكون المبلغ النهائي أرخص ؛
           * قائمة الشحن: تكاليف الشحن للعناصر والحقول على النحو التالي:
                   ** id: المعرف الفريد لطريقة الشحن ؛
                   ** name: اسم طريقة الشحن ؛
                   ** logo: عنوان URL الخاص بالشعار لطريق الشحن ؛
                   ** description: وصف طريقة الشحن ؛
                   ** website: الموقع الإلكتروني لطريقة الشحن ؛
                   ** transittime: وصف الوقت الشحن للسلع؛
                   ** shippingcost: تكلفة الشحن للسلع؛
واجهة 8: إنشاء طلب
    (أ) URL: /openapi/order!createOrder.do 
    (ب) المعلمات: 
           * siteNumber: لديك رقم طلب خاص أو رقم مرجعي إضافي آخر إلى أمر SUNSKY ، اختياري. الحد الأقصى للطول: 32 حرفًا.
           * useBalanceOnly: إذا تم تعيينه على "true" ، يجب أن يكون لديك رصيد كافٍ على موقع SUNSKY ، وإلا سيتم طرح exSpiton من "INSUFFICENT_BALANCE".
                    إذا تم التعيين على "false" ، فسيتم إنشاء الطلب باستخدام طريقة الدفع الخاصة بالتحويل المصرفي عندما لا يكون لديك رصيد كافٍ. تعيين افتراضي إلى false ، اختياري ؛
           * vatNumber: ظريبه الشراء؛
           * coupon: يمكن استخدام رمز القسيمة ؛
           * deliveryAddress.countryId: المعرّف الفريد للبلد ؛
           * deliveryAddress.state: رمز الولاية لعنوان الشحن ، راجع "/openapi/order!getCountries.do". 
                   إذا لم تكن هناك معلومات خاصة بالدولة ، فالرجاء إدخالها يدويًا. الحد الأقصى للطول: 40 حرفًا ؛
           * deliveryAddress.city: مدينة عنوان الشحن. الحد الأقصى للطول: 40 حرفًا ؛
           * deliveryAddress.company: اسم الشركة لعنوان الشحن ، اختياري. الحد الأقصى للطول: 100 حرفًا ؛
           * deliveryAddress.address: عنوان الشارع لعنوان الشحن. الحد الأقصى للطول: 100 حرفًا ؛
           * deliveryAddress.address2: سطر العنوان 2 من عنوان الشحن ، اختياري. الحد الأقصى للطول: 100 حرفًا ؛
           * deliveryAddress.postcode: الرمز البريدي / الرمز البريدي لعنوان الشحن. الحد الأقصى للطول: 20 حرفًا ؛
           * deliveryAddress.receiver: الاسم الكامل للمستلم. الحد الأقصى للطول: 32 حرفًا ؛
           * deliveryAddress.telephone: هاتف الاتصال الخاص بالمستقبل ، اختياري ، لكن موصى به. الحد الأقصى للطول: 20 حرفًا ؛
           * deliveryAddress.shippingWayId: المعرّف الفريد لطريقة الشحن.
                   يمكنك الحصول على قائمة طريقة الشحن بالاتصال على "/openapi/order!getPricesAndFreights.do" ، والحصول على خاصية المعرف من "freightList" في النتيجة ؛
            * deliveryAddress.shipment: drop - dropshipping؛ بالجملة - شراء لنفسك ، اختياري. التعيين الافتراضي على "wholesale" ؛
            * عناصر # عناصر لا توجد عناصر #: الكمية: قائمة العناصر لإنشاء أمر.
                    ** رقم # هو رقم صحيح لتمييز العناصر ، أي البنود .1 رقم العنصر ، البنود .2 رقم العنصر ...
                    ** itemNo: البند رقم المنتج ؛
                    ** qty: الكمية لهذا البند ؛
    (ج) النتيجة:
           ملخص:
            * إنشاء أمر SUNSKY مع العناصر ومعلومات عنوان التسليم.
            * يرجى الاتصال بـ SUNSKY للتحقق من حساب موقع الويب الخاص بك لإنشاء أمر.
           مجالات:
            * number: رقم الطلب ؛
            * status: حالة الطلب. انظر الملحق ج ؛
            * amount: المبلغ الفرعي للبنود ؛
            * shippingcost: تكلفة الشحن من النظام ؛
            * totalAmount: المبلغ الإجمالي للطلب. totalAmount = كمية + shippingCost.
            * siteNumber: لديك رقم طلب خاص أو رقم مرجعي إضافي آخر إلى أمر SUNSKY ، اختياري. الحد الأقصى للطول: 32 حرفًا.
            * vatNumber: ظريبه الشراء؛
            * coupon: يمكن استخدام رمز القسيمة ؛
            * packStatus: 0-Preparing؛ 1-التعبئة والتغليف، 2-معبأة في الغالب؛ 3 - تعبئتها وعلى استعداد للسفينة ؛
            * trackingNumber: رقم تتبع النظام ؛
            * gmtCreated: وقت الإنشاء للطلب ، بالتنسيق 'MM / dd / yyyy HH: mm' (أي 10/31/2013 05:01)؛
            * gmtPaid: الوقت المدفوع للطلب ، بالتنسيق 'MM / dd / yyyy HH: mm' (أي 10/31/2013 05:01) ؛
            * gmtShipped: الوقت المستغرق للطلب ، بالتنسيق 'MM / dd / yyyy HH: mm' (أي 10/31/2013 05:01)؛
            * deliveryAddress. *: معلومات عنوان الشحن. انظر "/openapi/order!createOrder.do '؛
                   فايلز إضافية:
                    ** shippingWay.id: معرف فريد لطريقة الشحن.
                    ** shippingWay.name: اسم طريقة الشحن؛
            * detailList: صفيف المادة بالترتيب والحقول على النحو التالي:
                    ** productId: المعرف الفريد للمنتج ؛
                    ** itemNo: البند رقم المنتج ؛
                    ** title: اسم المنتج ؛
                    ** qty: الكمية لهذا البند ؛
                    ** price: سعر الوحدة النهائي لهذا البند ؛
                    ** amount: المبلغ الإجمالي الفرعي النهائي لهذا البند ؛
                    **scaned: 0-غير جاهزة لحزم ؛ 1 - جاهز لحزمة ؛
                    ** delayToShip: 0-Normal؛ 1-تأجيل الشحن
واجهة 9: طلبات البحث
    (أ) URL: /openapi/order!getOrderList.do 
    (ب) المعلمات:
          * pageSize: حجم صفيف أوامر عاد ، تعيين الافتراضي إلى 40 ، الحد الأقصى هو 100 ؛
            * page: رقم الصفحة ، الافتراضي تعيين إلى 1؛
            * status: حالة الطلب ، اختياري. انظر الملحق ج ؛
            * siteNumber: اختياري. انظر "/openapi/order!createOrder.do '؛
            * gmtCreatedStart: لجلب الأوامر المنشأة بعد (بما في ذلك) 'gmtCreatedStart' ، بتنسيق MM / dd / yyyy (أي 10/31/2013) ، اختياري ؛
            * gmtCreatedEnd: جلب الطلبات التي تم إنشاؤها قبل (بما في ذلك) 'gmtCreatedEnd' ، بتنسيق MM / dd / yyyy (أي 10/31/2013) ، اختياري ؛
           ملخص:
            * تعيد واجهة برمجة التطبيقات هذه الطلبات التي تطابق الشروط التي حددتها.
            مجالات:
            *  total: يتطابق رقم الطلب الإجمالي مع الشروط التي حددتها.
            * pageCount: رقم الطلب الإجمالي ، محسوبًا بالإجمالي و pageSize.
            * result: يحتوي مصفوفة على سجلات الطلبات ، راجع "/openapi/order!createOrder.do" للحصول على التفاصيل.
                      لا يتم إرجاع "detailList" من خلال هذه الواجهة ، يرجى استخدام "/openapi/order!getOrderDetails.do" للحصول على معلومات العناصر.
واجهة 10: جلب تفاصيل الطلب
    (أ) URL: /openapi/order!getOrderDetails.do 
    (ب) المعلمات:
          * number: رقم طلب SUNSKY ؛     
    (ج) النتيجة:
           ملخص:
            * تعيد واجهة برمجة التطبيقات هذه المعلومات الكاملة للطلب المحدد.
            مجالات:
            * See '/openapi/order!createOrder.do'؛
الواجهة 11: تحقق من رصيدك على SUNSKY
    (أ) URL: /openapi/order!getBalance.do 
    (ب) المعلمات: 
           NONE      
    (ج) النتيجة:
           ملخص:
            * تعيد واجهة برمجة التطبيقات هذه رصيدك على SUNSKY.
            مجالات:
            تحتوي السلسلة فقط على رصيدك ، أي "1200.00".

واجهة 12: احصل على سجل توازنك
    (أ) URL: /openapi/order!getBillList.do 
    (ب) المعلمات:
          * pageSize: حجم صفيف الفواتير عاد ، تعيين الافتراضي إلى 40 ، الحد الأقصى هو 100 ؛
            * page: رقم الصفحة ، الافتراضي تعيين إلى 1؛
            * gmtCreatedStart: لجلب الفواتير التي تم إنشاؤها بعد (بما في ذلك) 'gmtCreatedStart' ، في تنسيق MM / dd / yyyy (أي 10/31/2013) ، اختياري ؛
            * gmtCreatedEnd: إحضار الفواتير التي تم إنشاؤها قبل (بما في ذلك) 'gmtCreatedEnd' ، بتنسيق MM / dd / yyyy (أي 10/31/2013) ، اختياري ؛    (c) Result:
          ملخص:
            * تعيد واجهة برمجة التطبيقات هذه الفواتير التي تطابق الشروط التي حددتها.
           مجالات:
            * total: يتطابق رقم الفاتورة الإجمالي مع الشروط التي حددتها.
            * pageCount: إجمالي رقم الفاتورة ، محسوبًا بالإجمالي و pageSize.
            * result: يحتوي صفيف على فواتير. الحقول على النحو التالي:
                      * txType: prepay / createOrder / payForOrder / cancelOrder؛
                      * refId: الأمر # المرتبط بالفاتورة ، إذا كان txType هو createOrder / payForOrder / cancelOrder؛
                      * amount:: تم تغيير المبلغ بعد المعاملة ؛
                      * balance: مبلغ الرصيد في SUNSKY بعد المعاملة ؛
                      * gmtCreated: وقت إنشاء الفاتورة بالتنسيق 'MM / dd / yyyy HH: mm' (أي 10/31/2013 05:01)؛
واجهة 13: احصل على العناصر الساخنة
    (أ) URL: /openapi/stats!getHotItems.do 
    (ب) المعلمات: 
          * countryId: المعرّف الفريد للبلد ؛   
   (ج) النتيجة:
            ملخص:
            * تعيد API هذه قائمة العناصر الساخنة في البلد المحدد.
            مجالات:
            * itemNo: العنصر # المنتج.

واجهة 14: احصل على قائمة القسيمة
    (أ) URL: /openapi/coupon!getList.do 
   (ب) المعلمات:
           * pageSize: حجم صفيف القسائم عاد ، تعيين الافتراضي إلى 40 ، الحد الأقصى هو 100 ؛
           * page: رقم الصفحة ، الافتراضي تعيين إلى 1؛
   (ج) النتيجة:
           ملخص:
           * تعيد واجهة برمجة التطبيقات هذه القسائم التي تطابق الشروط التي حددتها.
           مجالات:
           * total: يتطابق رقم الكوبون الإجمالي مع الشروط التي حددتها.
           * pageCount: إجمالي رقم القسيمة ، محسوبًا بالإجمالي و pageSize.
           * result: يحتوي صفيف على قسائم. الحقول على النحو التالي:
                    code: رمز القسيمة
                     * description: وصف الكوبون لشرح كيفية استخدام الكوبون ؛
                     * startTime: وقت بدء الكوبون ، بتنسيق "MM / dd / yyyy HH: mm" (أي 10/31/2013 05:01) ؛
                     * endTime: وقت انتهاء القسيمة ، بالتنسيق "MM / dd / yyyy HH: mm" (أي 10/31/2013 05:01) ؛
                     * personLimit: الأوقات التي يمكن لشخص واحد استخدام القسيمة ؛
                     * qty: يمكن استخدام كمية البند التي يمكن استخدامها في القسيمة للحصول على خصم ؛
                     *  discountType:
                                   1 - مبلغ مخفض ثابت
                                   2 - خصم في النسبة المئوية ؛
                                   3 - سعر ثابت
                     * discount: وفقًا لـ discountType المختلف ، تعني القيمة المقابلة:
                                   1 - المبلغ المخفض (سلسلة) ؛
                                   2 - النسبة المئوية (السلسلة) بعد خصمها ، 90 تعني 10٪ إيقاف ؛
                                   3 - السعر النهائي (سلسلة) ؛
                     * targetType:
                                   1 - الفئة
                                   2 - المنتج
                                   3 - ترتيب الحد الأدنى للطلب ؛
                                   4 - العلامة التجارية.
                     * target: وفقًا إلى targetType مختلف ، تكون القيمة المقابلة كما يلي:
                                   1 - قائمة json الفئة (سلسلة) ، أي [{id: 'category id' ، الاسم: 'Category name'}]
                                   2 - قائمة json للمنتج (سلسلة) ، أي [{id: 'معرف المنتج' ، الاسم: 'Product name' ، itemNo: 'Item #'}]
                                   3 - عتبة مبلغ الأمر (السلسلة) ، أي 200 ؛
                                   4 - قائمة json للعلامة التجارية (string) ، أي [{name: 'HAWEEL'}]؛
الملحق أ: حالة الفئة
     0 - غير صالح
     1 - صالح
     2 - المحذوفة
الملحق ب: حالة المنتج

     0 - غير صالح
     1 - صالح
     2 - المحذوفة
     3 - غير متوفر
الملحق ج: حالة الطلب

     1 - غير مدفوع
     2 - مدفوع
     3 - تم الشحن
     4 - ملغى
     5 - تسليمها
الملحق د: كود العينة (Java ، PHP)

     OpenApiService.zip
الملحق هـ: مجموعة تطوير البرامج (SDK

**Comment by progressify** [comment]
Hi @zz7iiu 
Can you write in english? I don't undestand your lang
