### ISSUE TITLE
Present Status of pysunsky

### ISSUE THREAD

**Issue by conaldakeh** [progressify/pysunsky#2]
Hi Antonio,

Trust you're doing well!

I will like to confirm if the code is presently working with the current Sunsky API? (Using 'TESTKEY' & 'TESTSECRET' as the Key and Secret)

Also, is there an email I can reach you on?

Hope to hear from you soonest. Thank you.

Kind Regards,
Chiedu.

**Comment by progressify** [comment]
Hi 👋

Thanks for using my SDK :)

I have now tested the SDK with my key and secret and all works great :)

Sorry,  'TESTKEY' and 'TESTSECRET' are not valid api key and secret. 
You must contact your sunsky sales manager and he will give you your personal API key and secret.

**Comment by conaldakeh** [comment]
Thanks for your swift reply.

Thing is, I demanded for a test integration before a commercial key and secret is gotten.

Are you saying your SDK can't work for a 'test' integration?

Awaiting your swift response. Thank you.

**Comment by progressify** [comment]
![image](https://user-images.githubusercontent.com/11472632/131718900-93022247-3d49-43c3-a855-22b083e0f887.png)

Oh sorry, it works with 'TESTKEY' and 'TESTSECRET' 💪
