### ISSUE TITLE
API SUNSKY

### ISSUE THREAD

**Issue by ParsiOne** [progressify/pysunsky#3]
Hi Antonio,

Could you create sunsky api for me?

**Comment by progressify** [comment]
Hi @ParsiOne
Yes, what type of api you need?

**Comment by ParsiOne** [comment]
ı need the connect sunsky website for download the bulk products

**Comment by progressify** [comment]
Do you want to sync sunsky products with your site?

**Comment by ParsiOne** [comment]
yes

**Comment by progressify** [comment]
I read your email, but your email provider rejects my reply.
Please contact me [here](https://www.linkedin.com/in/antonio-porcelli-progressify/) 

Bye :)
AP

**Comment by RitikIndia** [comment]
I want to Import Products to my website in  Bulk, Please Help!
