### ISSUE TITLE
How it does work? what is the steps that I have to follow? thanks in advance

### ISSUE THREAD

**Issue by leofloresh** [progressify/pysunsky#4]

**Comment by progressify** [comment]
Hi
[Here](https://github.com/progressify/pysunsky/blob/master/tests/test_api_service.py) you can find the examples of usage of this library 🙂

**Comment by leofloresh** [comment]
Hi thanks

I got this error

from pysunsky import OpenApiService
ModuleNotFoundError: No module named 'pysunsky'

thanks in advance, regards

**Comment by progressify** [comment]
Sure, you must install the library first.
Follow this instructions:
https://github.com/progressify/pysunsky#installation

Or simply run:
```pip install pysunsky```

**Comment by nadershehata95** [comment]
Hey I have the same problem don't know how to run it and I followed this reply

> Hi [Here](https://github.com/progressify/pysunsky/blob/master/tests/test_api_service.py) you can find the examples of usage of this library 🙂

But there is just the class defined and its methods so if I want to use this test_get_product_details() function how can I run it? I want to run these functions how can I?

**Comment by progressify** [comment]
[Here](https://github.com/progressify/pysunsky#usage) you can find how to use this library :)
I suggest to learn some python basic before to use it. This library is for developers.

If you think I can help you in some way, consider to ask me a consulence.
Bye 👋

**Comment by nadershehata95** [comment]
> [Here](https://github.com/progressify/pysunsky#usage) you can find how to use this library :) I suggest to learn some python basic before to use it. This library is for developers.
> 
> If you think I can help you in some way, consider to ask me a consulence. Bye 👋

I know Python yes and I understand the test example but I can't run it 😂 Okay I have now the class and methods implemented now, how can I run a function to get the data?! I tried to define new object of the class and call the function I want but I couldn't get any data?!

**Comment by nadershehata95** [comment]
> > [Here](https://github.com/progressify/pysunsky#usage) you can find how to use this library :) I suggest to learn some python basic before to use it. This library is for developers.
> > If you think I can help you in some way, consider to ask me a consulence. Bye 👋
> 
> I know Python yes and I understand the test example but I can't run it 😂 Okay I have now the class and methods implemented now, how can I run a function to get the data?! I tried to define new object of the class and call the function I want but I couldn't get any data?!

Please I need help in running it!! 😢 @progressify

**Comment by progressify** [comment]
I think I can't help you if you don't post an error or some example of your code

**Comment by nadershehata95** [comment]
Bro I can't even run the code! 😂 I am asking for a complete guide to run the code is it that difficult for you! how can I get error and I didn't run it? I have the full classes and example now what! need to scrape data how can I run it?! from shell, creating an object of the class then running the code or what!!! you didn't share the complete guide you just shared the class implementations!!

**Comment by progressify** [comment]
In the `tests` folder you can find a simple python unittest class.
I really don't understand your problems!

You can run it with this command:
```
python -m unittest tests.test_api_service.TestApi
```
Nothing strange I think.

**Comment by nadershehata95** [comment]
You know what that's exactly what I was asking about how to run it 😂 now I
can run it, thank you.

**Comment by progressify** [comment]
As I said, I suggest you study the basics of python, unittest is a widely used and well-known utility.
Glad you fixed it, bye.
