### ISSUE TITLE
Get the data as CSV or JSON file

### ISSUE THREAD

**Issue by nadershehata95** [progressify/pysunsky#6]
Hey, I know I asked a lot but I really need your help.
Now I ran the test successfully and get that the test passed
![image](https://github.com/progressify/pysunsky/assets/103794068/e7408c6f-38bd-479e-9bf2-c62732c8e9a7)

Now I don't need to test the API I need to run the API to get my data as a CSV or JSON file, how can I do that? should I create an object of class TestApi and call the function I want and replace this
`self.assertEqual(json.loads(result)['result'], 'success')`
with
`result.json()`
for example or what? because I tried this and I get the JSON file but not sure that's the best way to do that, I am sorry I ask a lot but please help.

**Comment by progressify** [comment]
Hi Nader
I am really happy to know that you are now able to use my SDK.
The question that you asked is not concerning the library, but a business logic.

I have an email in my inbox from you, we will continue in private this conversation.
